name: Pipeline CI

on:
  push:
    branches: [principale]

jobs:
  gitleaks:
     runs-on: ubuntu-latest
    steps:
      - name: Caisse
        uses: actions/checkout@v4

      - name: Lancer une analyse Gitleaks
        uses: zricethezav/gitleaks-action@v2

      - name: Télécharger le rapport Gitleaks
        uses: actions/upload-artifact@v4
        with:
          name: rapport-gitleaks
          chemin: résultats.sarif
