nom: Pipeline CI

sur:
  pousser:
    branches: [principale]

emplois:
  gitleaks:
    fonctionne sous: ubuntu-latest
    étapes:
      - nom: Caisse
        utilise: actions/checkout@v4

      - nom: Lancer une analyse Gitleaks
        utilise: zricethezav/gitleaks-action@v2

      - nom: Télécharger le rapport Gitleaks
        utilise: actions/upload-artifact@v4
        avec:
          nom: rapport-gitleaks
          chemin: résultats.sarif
