name: Pipeline CI

on:
  push:
    branches: [principale]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Lancer une analyse Gitleaks
      uses: zricethezav/gitleaks-action@v2
      with:
        sarif-report: results.sarif
    - name: Télécharger le rapport Gitleaks
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: results.sarif


        # Login Docker Hub
- name:Scan Docker image with Trivy
uses: aquasecurity/trivy-action@0.20.0
with:
image-ref: democyber:latest
format: 'table'
exit-code: '1'
severety: 'CRITICAL,HIGH'
# Build Docker image
- name: Build Docker image
run: docker build -t democyber:latest .
